// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WebsocketWrapper.proto

package kcwiki_msgtransfer_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Websocket_ProtoType int32

const (
	Websocket_SYSTEM     Websocket_ProtoType = 0
	Websocket_NON_SYSTEM Websocket_ProtoType = 1
)

var Websocket_ProtoType_name = map[int32]string{
	0: "SYSTEM",
	1: "NON_SYSTEM",
}
var Websocket_ProtoType_value = map[string]int32{
	"SYSTEM":     0,
	"NON_SYSTEM": 1,
}

func (x Websocket_ProtoType) String() string {
	return proto.EnumName(Websocket_ProtoType_name, int32(x))
}
func (Websocket_ProtoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_WebsocketWrapper_de9e4c5be5935ecd, []int{0, 0}
}

type Websocket_ProtoCode int32

const (
	Websocket_FAIL    Websocket_ProtoCode = 0
	Websocket_SUCCESS Websocket_ProtoCode = 1
	Websocket_ERROR   Websocket_ProtoCode = 2
)

var Websocket_ProtoCode_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
	2: "ERROR",
}
var Websocket_ProtoCode_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x Websocket_ProtoCode) String() string {
	return proto.EnumName(Websocket_ProtoCode_name, int32(x))
}
func (Websocket_ProtoCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_WebsocketWrapper_de9e4c5be5935ecd, []int{0, 1}
}

type Websocket struct {
	ProtoType            Websocket_ProtoType `protobuf:"varint,1,opt,name=proto_type,json=protoType,proto3,enum=kcwiki.msgtransfer.protobuf.Websocket_ProtoType" json:"proto_type,omitempty"`
	ProtoCode            Websocket_ProtoCode `protobuf:"varint,2,opt,name=proto_code,json=protoCode,proto3,enum=kcwiki.msgtransfer.protobuf.Websocket_ProtoCode" json:"proto_code,omitempty"`
	ProtoModule          string              `protobuf:"bytes,3,opt,name=proto_module,json=protoModule,proto3" json:"proto_module,omitempty"`
	ProtoPayload         []byte              `protobuf:"bytes,4,opt,name=proto_payload,json=protoPayload,proto3" json:"proto_payload,omitempty"`
	Timestamp            int64               `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign                 string              `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Websocket) Reset()         { *m = Websocket{} }
func (m *Websocket) String() string { return proto.CompactTextString(m) }
func (*Websocket) ProtoMessage()    {}
func (*Websocket) Descriptor() ([]byte, []int) {
	return fileDescriptor_WebsocketWrapper_de9e4c5be5935ecd, []int{0}
}
func (m *Websocket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Websocket.Unmarshal(m, b)
}
func (m *Websocket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Websocket.Marshal(b, m, deterministic)
}
func (dst *Websocket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Websocket.Merge(dst, src)
}
func (m *Websocket) XXX_Size() int {
	return xxx_messageInfo_Websocket.Size(m)
}
func (m *Websocket) XXX_DiscardUnknown() {
	xxx_messageInfo_Websocket.DiscardUnknown(m)
}

var xxx_messageInfo_Websocket proto.InternalMessageInfo

func (m *Websocket) GetProtoType() Websocket_ProtoType {
	if m != nil {
		return m.ProtoType
	}
	return Websocket_SYSTEM
}

func (m *Websocket) GetProtoCode() Websocket_ProtoCode {
	if m != nil {
		return m.ProtoCode
	}
	return Websocket_FAIL
}

func (m *Websocket) GetProtoModule() string {
	if m != nil {
		return m.ProtoModule
	}
	return ""
}

func (m *Websocket) GetProtoPayload() []byte {
	if m != nil {
		return m.ProtoPayload
	}
	return nil
}

func (m *Websocket) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Websocket) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func init() {
	proto.RegisterType((*Websocket)(nil), "kcwiki.msgtransfer.protobuf.Websocket")
	proto.RegisterEnum("kcwiki.msgtransfer.protobuf.Websocket_ProtoType", Websocket_ProtoType_name, Websocket_ProtoType_value)
	proto.RegisterEnum("kcwiki.msgtransfer.protobuf.Websocket_ProtoCode", Websocket_ProtoCode_name, Websocket_ProtoCode_value)
}

func init() {
	proto.RegisterFile("WebsocketWrapper.proto", fileDescriptor_WebsocketWrapper_de9e4c5be5935ecd)
}

var fileDescriptor_WebsocketWrapper_de9e4c5be5935ecd = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x97, 0xfd, 0xd3, 0xdc, 0xcd, 0x52, 0xf2, 0x20, 0x01, 0x7d, 0xa8, 0xf5, 0xc1, 0xbe,
	0x58, 0x44, 0x3f, 0x81, 0x1b, 0x13, 0x04, 0xb7, 0x96, 0x74, 0x32, 0x7c, 0x1a, 0xfd, 0x93, 0x8d,
	0xd2, 0x75, 0x09, 0x6d, 0x86, 0xf4, 0xd3, 0x2b, 0x4b, 0xd7, 0xee, 0x4d, 0xf0, 0xed, 0xe4, 0x9c,
	0x7b, 0x7e, 0xe4, 0x5e, 0xb8, 0x5e, 0xf1, 0xa8, 0x14, 0x71, 0xc6, 0xd5, 0xaa, 0x08, 0xa5, 0xe4,
	0x85, 0x2b, 0x0b, 0xa1, 0x04, 0xb9, 0xc9, 0xe2, 0xef, 0x34, 0x4b, 0xdd, 0xbc, 0xdc, 0xaa, 0x22,
	0xdc, 0x97, 0x9b, 0x26, 0x89, 0x0e, 0x1b, 0xfb, 0xa7, 0x0b, 0xb8, 0xed, 0x11, 0x0f, 0x40, 0x27,
	0x6b, 0x55, 0x49, 0x4e, 0x91, 0x85, 0x1c, 0xe3, 0xf9, 0xc9, 0xfd, 0xa3, 0xef, 0xb6, 0x5d, 0xd7,
	0x3f, 0x5a, 0xcb, 0x4a, 0x72, 0x86, 0x65, 0x23, 0xcf, 0xc0, 0x58, 0x24, 0x9c, 0x76, 0xff, 0x0f,
	0x9c, 0x8a, 0xa4, 0x01, 0x1e, 0x25, 0xb9, 0x83, 0x71, 0x0d, 0xcc, 0x45, 0x72, 0xd8, 0x71, 0xda,
	0xb3, 0x90, 0x83, 0xd9, 0x48, 0x7b, 0x73, 0x6d, 0x91, 0x7b, 0xb8, 0xaa, 0x47, 0x64, 0x58, 0xed,
	0x44, 0x98, 0xd0, 0xbe, 0x85, 0x9c, 0x31, 0xab, 0x7b, 0x7e, 0xed, 0x91, 0x5b, 0xc0, 0x2a, 0xcd,
	0x79, 0xa9, 0xc2, 0x5c, 0xd2, 0x81, 0x85, 0x9c, 0x1e, 0x3b, 0x1b, 0x84, 0x40, 0xbf, 0x4c, 0xb7,
	0x7b, 0x3a, 0xd4, 0x74, 0xad, 0xed, 0x07, 0xc0, 0xed, 0x8a, 0x04, 0x60, 0x18, 0x7c, 0x05, 0xcb,
	0xd9, 0xdc, 0xec, 0x10, 0x03, 0x60, 0xe1, 0x2d, 0xd6, 0xa7, 0x37, 0xb2, 0x1f, 0x4f, 0x83, 0xfa,
	0xbf, 0x97, 0xd0, 0x7f, 0x7b, 0x7d, 0xff, 0x30, 0x3b, 0x64, 0x04, 0x17, 0xc1, 0xe7, 0x74, 0x3a,
	0x0b, 0x02, 0x13, 0x11, 0x0c, 0x83, 0x19, 0x63, 0x1e, 0x33, 0xbb, 0x13, 0x1b, 0x8c, 0x76, 0x79,
	0x2d, 0x26, 0x46, 0x7b, 0x03, 0xcd, 0xf1, 0x51, 0x34, 0xd4, 0xc1, 0xcb, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0x1b, 0x03, 0x53, 0xe3, 0x01, 0x00, 0x00,
}
